#!/usr/bin/env python3
"""Living documentation generator.

Documentation that is written by hand drifts from the code within days, and
stale docs are worse than none: they actively mislead. So the parts of the docs
that describe *structure* are generated from the repository itself, and CI fails
if the committed output no longer matches what the generator produces.

Borrowed from deepseek-harness, which generates its config and plugin catalogs
into docs/ and gates on them in `scripts/`.

Generated regions are delimited so hand-written prose can live alongside:

    <!-- BEGIN:REPOMAP -->   ... generated, do not edit ...   <!-- END:REPOMAP -->

Usage:
    python scripts/gen_docs.py            # rewrite generated regions
    python scripts/gen_docs.py --check    # exit 1 if any region is stale (CI)
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]

# Directory -> (one-line purpose, sort order)
PURPOSE = {
    "src/emlnca": "EML-family primitives, stability instrumentation",
    "harness": "provenance, metrics contract, invariant enforcement",
    "tests": "invariants (hard-fail) -- never research metrics",
    "security": "zero-dependency secret and identifier scanner",
    ".githooks": "pre-commit, commit-msg, pre-push guards",
    "scripts": "repo gates and generators",
    "configs/frozen": "reference configs -- assertions here are INVARIANTS",
    "configs/experimental": "working configs -- assertions here are METRICS",
    "experiments": "the experiment ladder, rung by rung",
    "threads": "parallel research threads: fork, run, converge",
    "journal": "dated research log -- what was tried, what it showed",
    "literature": "the paper corpus and its hyperlinked index",
    "viz/three": "interactive WebGL viewer",
    "viz/manim": "concept explainer animations",
    "results": "metrics.json per run (artifacts are NOT committed)",
    "docs": "generated catalogs and long-form notes",
    "skills": "provider-agnostic task recipes for agents",
    ".github/workflows": "CI: security gate, guard matrix, hook effectiveness",
}

SKIP_DIRS = {".git", ".venv", "node_modules", "__pycache__", ".pytest_cache",
             ".ruff_cache", "dist", "build", ".mypy_cache", "media"}


def git(*args: str) -> str:
    r = subprocess.run(["git", *args], capture_output=True, encoding="utf-8",
                       errors="replace", cwd=REPO, check=False)
    return (r.stdout or "").strip()


def tracked_files() -> list[str]:
    return [f for f in git("ls-files").splitlines() if f.strip()]


# ---------------------------------------------------------------- repo map

def build_repo_map() -> str:
    files = tracked_files()
    dirs: dict[str, int] = {}
    for f in files:
        parts = Path(f).parts
        for depth in (1, 2):
            if len(parts) > depth:
                d = "/".join(parts[:depth])
                if not any(p in SKIP_DIRS for p in parts):
                    dirs[d] = dirs.get(d, 0) + 1

    # Keep a directory only if it has an explicit purpose, or is a top-level
    # directory with content. Prevents the map degenerating into `ls -R`.
    keep = {d: n for d, n in dirs.items()
            if d in PURPOSE or ("/" not in d and n > 0)}

    lines = ["```", "eml-nca/"]
    for d in sorted(keep):
        depth = d.count("/")
        indent = "  " * (depth + 1)
        name = d.split("/")[-1] + "/"
        purpose = PURPOSE.get(d, "")
        n = keep[d]
        left = f"{indent}{name:<22}"
        unit = "file " if n == 1 else "files"
        lines.append(f"{left} {n:>3} {unit}  {purpose}".rstrip())
    lines.append("```")
    lines.append("")
    lines.append(f"_{len(files)} tracked files. "
                 f"Generated by `scripts/gen_docs.py` -- do not edit by hand._")
    return "\n".join(lines)


# ------------------------------------------------------------ test catalog

def build_test_catalog() -> str:
    rows = []
    total = 0
    for path in sorted((REPO / "tests").glob("test_*.py")):
        text = path.read_text(encoding="utf-8")
        names = re.findall(r"^def (test_\w+)", text, re.MULTILINE)
        doc = ""
        m = re.search(r'^"""(.+?)$', text, re.MULTILINE)
        if m:
            doc = m.group(1).strip().rstrip(".")
        rows.append((path.name, len(names), doc))
        total += len(names)
    out = ["| file | tests | covers |", "|---|---:|---|"]
    for name, n, doc in rows:
        out.append(f"| `{name}` | {n} | {doc} |")
    out.append(f"| **total** | **{total}** | all hard-failing invariants |")
    return "\n".join(out)


# ---------------------------------------------------------- thread catalog

def load_threads() -> list[dict]:
    reg = REPO / "threads" / "registry.json"
    if not reg.exists():
        return []
    return json.loads(reg.read_text(encoding="utf-8")).get("threads", [])


def build_thread_catalog() -> str:
    threads = load_threads()
    if not threads:
        return "_No threads registered yet._"
    status_icon = {"active": "●", "parked": "◌", "converged": "◆",
                   "abandoned": "✗", "proposed": "○"}
    out = ["| id | status | hypothesis | parent | verdict |",
           "|---|---|---|---|---|"]
    for t in threads:
        icon = status_icon.get(t.get("status", ""), "?")
        out.append(
            f"| `{t['id']}` | {icon} {t.get('status', '?')} "
            f"| {t.get('hypothesis', '')} "
            f"| {t.get('parent') or '-'} "
            f"| {t.get('verdict') or '_open_'} |"
        )
    return "\n".join(out)


# ------------------------------------------------------ literature catalog

def build_literature_catalog() -> str:
    idx = REPO / "literature" / "index.json"
    if not idx.exists():
        return "_Literature not fetched yet. Run `python scripts/fetch_literature.py`._"
    papers = json.loads(idx.read_text(encoding="utf-8")).get("papers", [])
    out = ["| # | date | paper | role |", "|---|---|---|---|"]
    for p in papers:
        link = f"[{p['title']}](https://arxiv.org/abs/{p['arxiv']})"
        out.append(f"| {p['n']} | {p['date']} | {link} | {p.get('role', '')} |")
    return "\n".join(out)


# -------------------------------------------------------------- injection

REGIONS = {
    "REPOMAP": build_repo_map,
    "TESTCATALOG": build_test_catalog,
    "THREADS": build_thread_catalog,
    "LITERATURE": build_literature_catalog,
}


def inject(text: str, region: str, body: str) -> str:
    begin, end = f"<!-- BEGIN:{region} -->", f"<!-- END:{region} -->"
    pattern = re.compile(
        re.escape(begin) + r".*?" + re.escape(end), re.DOTALL
    )
    replacement = f"{begin}\n{body}\n{end}"
    if not pattern.search(text):
        return text
    return pattern.sub(lambda _: replacement, text)


def process(check: bool) -> int:
    targets = [p for p in REPO.glob("*.md")] + list((REPO / "docs").glob("*.md"))
    stale: list[str] = []
    written: list[str] = []

    for path in targets:
        if not path.is_file():
            continue
        original = path.read_text(encoding="utf-8")
        updated = original
        for region, builder in REGIONS.items():
            if f"<!-- BEGIN:{region} -->" in updated:
                updated = inject(updated, region, builder())
        if updated != original:
            if check:
                stale.append(str(path.relative_to(REPO)))
            else:
                path.write_text(updated, encoding="utf-8")
                written.append(str(path.relative_to(REPO)))

    if check:
        if stale:
            print("Generated documentation is STALE in:")
            for s in stale:
                print(f"  - {s}")
            print("\nRun:  python scripts/gen_docs.py")
            return 1
        print("generated docs: in sync")
        return 0

    if written:
        print("regenerated:")
        for w in written:
            print(f"  - {w}")
    else:
        print("generated docs: already current")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate living documentation")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if any generated region is stale (CI gate)")
    args = ap.parse_args()
    return process(check=args.check)


if __name__ == "__main__":
    sys.exit(main())
